version = 0.1
[eu-west-1]
[eu-west-1.deploy]
[eu-west-1.deploy.parameters]
stack_name = "twitter-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1973oc4egp22x"
s3_prefix = "twitter-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
