package model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;

@DynamoDBTable(tableName = "twitter_feeds")
public class TwitterDataStore {

    public static class DateConverter implements DynamoDBTypeConverter<Long, Date> {

        @Override
        public Long convert(Date object) {
            return object != null ? object.getTime() / 1000 : null;
        }

        @Override
        public Date unconvert(Long object) {
            return object != null ? new Date(object * 1000) : null;
        }
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    private String userId;
    private String twitterMessage;
    private Long version;
    private Date postedDate;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "userid")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "message")
    public String getTwitterMessage() {
        return twitterMessage;
    }

    public void setTwitterMessage(String twitterMessage) {
        this.twitterMessage = twitterMessage;
    }

    @DynamoDBAttribute(attributeName = "posted-date")
    @DynamoDBTypeConverted(converter = DateConverter.class)
    public Date getPostedDate() {
        return postedDate;
    }

    public void setPostedDate(Date postedDate) {
        this.postedDate = postedDate;
    }

    @DynamoDBVersionAttribute
    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }
}
